### ISSUE TITLE
Needs Updating due to Pain Day III

### ISSUE THREAD

**Issue by PatrickJnr** [xezno/sbox-quixel-bridge#6]
Needs an update because of Pain Day III, if I knew what to do I would have done so myself

`Object reference not set to an instance of an object.`

**Comment by xezno** [comment]
All tools are broken right now due to a general custom tools issue, see here: https://discord.com/channels/833983068468936704/977177359344082994/977286123225239652

**Comment by PatrickJnr** [comment]
Since we have it, I get a new Error:

`  A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null. (Parameter 'relativeTo'))
  Value cannot be null. (Parameter 'relativeTo')`

**Comment by xezno** [comment]
This is fixed in 67406fe54fb2eac96b16e46161e167f089f2f289 (will do a release in a second) but you should really set up the tool properly and select the addon you want to export to:

![image](https://user-images.githubusercontent.com/12881812/169655235-27451c7a-c2d8-4051-8915-c22ec446e556.png)

**Comment by PatrickJnr** [comment]
I did that beforehand, but yeah, thanks for fixing it.
