### ISSUE TITLE
Needs Updated

### ISSUE THREAD

**Issue by ImXaze** [xezno/sbox-quixel-bridge#7]
Recent S&Box updates broke the tool... Unless I'm crazy.

https://i.imgur.com/s3gYatd.png

Can't get much of anything working.

**Comment by xezno** [comment]
I can't repro this, what are you doing to cause this?

**Comment by ImXaze** [comment]
Base install on the latest version of s&box
Here's a video: 
https://streamable.com/i49xvn

Let me know if I'm missing something here.

**Comment by xezno** [comment]
Pushed a fix, download the repo zip and let me know if that fixes it for you

**Comment by JayarrG** [comment]
Decided to make an account for this since I am also interested in the tool

The issue seems to still persist. Same error as @XazeSyn provided

**Comment by xezno** [comment]
I did a bunch of testing and I think I got everything, this should be fixed now. Sorry for the delay
